### ISSUE TITLE
Generate default config to prevent NPE on first boot

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/MobLimiter#24]
``` yaml
Groups:
  Animals:
    ChunkLimit: 30
    ViewDistanceLimit: 150
    WarnOverLimit: true
    HORSE:
      Name: Horses
      ChunkLimit: 16
      ViewDistanceLimit: 150
    COW:
      Name: Cows
      ChunkLimit: 30
      ViewDistanceLimit: 150
    SHEEP:
      Name: Sheep
      ChunkLimit: 30
      ViewDistanceLimit: 150
    CHICKEN:
      Name: Chickens
      ChunkLimit: 30
      ViewDistanceLimit: 150
    PIG:
      Name: Pigs
      ChunkLimit: 30
      ViewDistanceLimit: 150
  Villagers:
    Name: Villagers and Golems
    ChunkLimit: -1
    ViewDistanceLimit: -1
    WarnOverLimit: true
    IRON_GOLEM:
      Name: Golems
      ChunkLimit: 4
      ViewDistanceLimit: 32
    VILLAGER:
      Name: Villagers
      ChunkLimit: 30
      ViewDistanceLimit: 90
EnabledWorlds:
- world
- world_nether
```

This needs to be added on first boot. Can be hardcoded for now, I don’t mind.
