### ISSUE TITLE
Rabbits

### ISSUE THREAD

**Issue by zuzzas** [CoreNetwork/MobLimiter#33]
Can you add a rabbit limit configuration option to "setting.yml" file?
I have no idea on how to add this option properly to the config file.

**Comment by riddle** [comment]
Definitely. I have it like this:

``` yaml
Groups:
  Animals:
    ChunkLimit: 30
    ViewDistanceLimit: 150
    WarnOverLimit: true
    HORSE:
      Name: Horses
      ChunkLimit: 30
      ViewDistanceLimit: 150
    COW:
      Name: Cows
      ChunkLimit: 30
      ViewDistanceLimit: 150
    SHEEP:
      Name: Sheep
      ChunkLimit: 30
      ViewDistanceLimit: 150
    CHICKEN:
      Name: Chickens
      ChunkLimit: 30
      ViewDistanceLimit: 150
    PIG:
      Name: Pigs
      ChunkLimit: 30
      ViewDistanceLimit: 150
    RABBIT:
      Name: Rabbits
      ChunkLimit: 30
      ViewDistanceLimit: 150
```
